"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const course_controller_1 = require("../controllers/course.controller");
const auth_1 = require("../middleware/auth");
const course_controller_2 = require("../controllers/course.controller");
const user_controller_1 = require("../controllers/user.controller");
const courseRouter = express_1.default.Router();
courseRouter.post("/create-course", user_controller_1.updateAccessToken, auth_1.isAuthenticated, (0, auth_1.authorizeRoles)("teacher"), course_controller_1.uploadCourse);
courseRouter.get("/get-all-comments", auth_1.isAuthenticated, (0, auth_1.authorizeRoles)("teacher"), course_controller_1.getAllCommentsForCourses);
courseRouter.put("/edit-course/:id", user_controller_1.updateAccessToken, auth_1.isAuthenticated, (0, auth_1.authorizeRoles)("teacher"), course_controller_1.editCourse);
courseRouter.get("/get-course/:id", course_controller_1.getSingleCourse);
courseRouter.get("/get-courses", course_controller_1.getAllCourses);
courseRouter.get("/get-course-content/:id", auth_1.isAuthenticated, course_controller_1.getCourseByUser);
courseRouter.put("/add-question", auth_1.isAuthenticated, course_controller_2.addQusetion);
courseRouter.put("/add-answer", auth_1.isAuthenticated, course_controller_2.addAnswer);
courseRouter.put("/add-review/:id", auth_1.isAuthenticated, course_controller_2.addReview);
courseRouter.put("/add-reply", auth_1.isAuthenticated, (0, auth_1.authorizeRoles)("admin", "teacher"), course_controller_2.addReplyToReview);
courseRouter.get("/get-all-course", auth_1.isAuthenticated, (0, auth_1.authorizeRoles)("admin"), course_controller_1.getAllCourses);
courseRouter.get("/get-admin-courses", auth_1.isAuthenticated, (0, auth_1.authorizeRoles)("admin"), course_controller_1.getAdminAllCourses);
courseRouter.delete("/delete-course/:id", auth_1.isAuthenticated, (0, auth_1.authorizeRoles)("admin", "teacher"), course_controller_1.deleteCourse);
courseRouter.post("/getVdoCipherOTP", course_controller_1.generateVideoUrl);
exports.default = courseRouter;
